apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  labels:
    app: django
data:
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "your-domain.com"
  DJANGO_CSRF_TRUSTED_ORIGINS: "https://your-domain.com"
  POSTGRES_DB: rcsg
  POSTGRES_USER: rcsg
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
